services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-somewordpress}
      MYSQL_DATABASE: ${DB_NAME:-wordpress}
      MYSQL_USER: ${DB_USER:-wordpress}
      MYSQL_PASSWORD: ${DB_PASSWORD:-wordpress}
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - "${WP_PORT:-8000}:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-wordpress}
      WORDPRESS_DB_NAME: ${DB_NAME:-wordpress}
    volumes:
      - wp_data:/var/www/html
      - ./wp-config.php:/var/www/html/wp-config.php
      # Mount the plugin: local dir -> container plugins dir
      - ./:/var/www/html/wp-content/plugins/zenadmin
      - ./php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5
    restart: always
    ports:
      - "${PMA_PORT:-8080}:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-somewordpress}

volumes:
  db_data:
  wp_data:
